app/application/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, HiddenField
from wtforms.validators import DataRequired


class SentimentPredictionForm(FlaskForm):
	body = TextAreaField("Answer", validators=[DataRequired()])
	submit_review = SubmitField('Review')
	submit_correct = SubmitField('Correct')
	submit_incorrect = SubmitField('Incorrect')
	prediction = HiddenField('Prediction')

app/application/__init__.py
from flask import Flask
from .config import Config
from .errors.routes import bp as error_bp
from .routes import bp as routes_bp


def create_app():

	app = Flask(__name__)
	app.config.from_object(Config)

	with app.app_context():
		app.register_blueprint(error_bp)
		app.register_blueprint(routes_bp)

		return app

app/application/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
import requests
import json
from .forms import SentimentPredictionForm


bp = Blueprint('routes', __name__)


@bp.route('/', methods=['GET'])
def home():
    return render_template('home.html')


@bp.route('/sentiment', methods=['GET', 'POST'])
def sentiment():
	form = SentimentPredictionForm()

	# user submitted prediction feedback
	if (request.form.get('submit_correct') or request.form.get('submit_incorrect')) and form.validate_on_submit():
		sentiment = {'prediction': request.form.get('prediction'),
					 'submit_correct': request.form.get('submit_correct'),
					 'submit_incorrect': request.form.get('submit_incorrect'),
					 'review': request.form.get('body')}
		requests.post("http://localhost:5001/prediction", json=sentiment)
		return redirect(url_for('routes.sentiment', reviewed=True))

	# user submitted review
	if request.form.get('submit_review') and form.validate_on_submit():
		review = {"review": request.form.get('body')}
		response = requests.post("http://localhost:5001/sentiment", json=review)
		if response.status_code == 200:
			form.prediction.data = response.json()
		return render_template('project_sentiment.html', form=form)

	return render_template('project_sentiment.html', form=form, reviewed=request.args.get('reviewed'))


@bp.route('/question', methods=['POST'])
def question():
	''' Returns a random question from the Question database
	'''
	response = requests.get("http://localhost:5001/question")
	question = response.json()
	return (question, 200) if question else 500

app/application/sentiment/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
import requests
from .forms import SentimentPredictionForm


bp = Blueprint('sentiment_routes', __name__)


@bp.route('/sentiment', methods=['GET', 'POST'])
def sentiment():
	form = SentimentPredictionForm()

	# user submitted prediction feedback
	if (request.form.get('submit_correct') or request.form.get('submit_incorrect')) and form.validate_on_submit():
		
		sentiment = get_sentiment(request.form.get('prediction'),
								  request.form.get('submit_correct'),
								  request.form.get('submit_incorrect'))
		entry = Sentiment(text=request.form.get('body'), sentiment=sentiment, correct=True)
		db.session.add(entry)
		db.session.commit()
		return redirect(url_for('sentiment_routes.sentiment', reviewed=True))

	# user submitted review
	if request.form.get('submit_review') and form.validate_on_submit():
		review = {"review": request.form.get('body')}
		prediction = requests.post("http://localhost:5001/sentiment", json=review)
		# TODO error handling
		form.prediction.data = prediction
		return render_template('project_sentiment.html', form=form)

	return render_template('project_sentiment.html', form=form, reviewed=request.args.get('reviewed'))


@bp.route('/question', methods=['POST'])
def question():
	''' Returns a random question from the Question database
	'''
	question = requests.get("http://localhost:5001/question")
	return (question, 200) if question else 500

app/application/templates/about.html
<div data-anchor="about" class="fp-section fp-auto-height-responsive">
    <div class="fp-section-inner pt-120 pt-lg-80 pt-md-80 pt-sm-80 pt-xs-50 pb-90 pb-lg-50 pb-md-50 pb-sm-50 pb-xs-20">
        <div class="container">
            <div class="row align-items-center">

                <!-- About Image -->
                <div class="about-image col-xl-6 col-12 mb-30"><img src="../static/theme/assets/images/self_one.png" alt=""></div>

                <!-- About Content -->
                <div class="about-content col-xl-6 col-12 mb-30">
                    <h3 class="block-title">About Me</h3>
                    <a>A few of my favorite algorithm families are <a href="https://blog.floydhub.com/introduction-to-genetic-algorithms/">genetic algorithms</a>,
                        <a href="">randomized algorithms</a>, <a href="">multi-agent search algorithms.<a/></p>

                    <!-- Personal Info -->
                    <ul class="personal-info">
                        <li><span>Spoken Languages</span>English, 日本語</li>
                        <li><span>Typed Languages</span>Java, Python, C++, Bash, Erlang, SQL</li>
                        <li><span>Specializations</span>software engineering, artificial intelligence, machine learning, robotics</li>
                        <li><span>Hobbies</span>astronomy, violin, soccer, trance music, Japanese language and culture</li>
                    </ul>

                </div>

            </div>
        </div>
    </div>
</div>

app/application/templates/base.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Kymry Burwell</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="../static/theme/assets/images/favicon.ico">

    <!-- CSS ============================================ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../static/theme/assets/css/bootstrap.min.css">
    <!-- Icon Font CSS -->
    <link rel="stylesheet" href="../static/theme/assets/css/fontawesome.min.css">
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="../static/theme/assets/css/plugins.css">
    <!-- Helper CSS -->
    <link rel="stylesheet" href="../static/theme/assets/css/helper.css">
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="../static/theme/assets/css/style.css">
    <!-- Modernizer JS -->
    <script src="../static/theme/assets/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>

<div class="main-wrapper has-side-header">

    <!-- Header Section Start -->
    <div class="header-section section d-block d-lg-none">
        <div class="container-fluid">
            <div class="row align-items-center">

                <!-- Logo -->
                <div class="header-logo col mt-40 mb-40"><a href="{{ url_for('routes.home') }}">Kymry Burwell・バーウェル　キムリー</a></div>
                <!-- Toggle Button -->
                <div class="header-toggle-btn col text-right"><button class="side-header-toggle"><span></span></button></div>

            </div>
        </div>
    </div><!-- Header Section End -->

    <!-- Side Header Overlay Start -->
    <div class="side-menu-overlay"></div><!-- Side Header Overlay End -->

    <!-- Side Header Start -->
    <div class="side-header custom-scroll">

        <!-- Side Header Inner Start -->
        <div class="side-header-inner">
            <button class="side-header-close d-block d-lg-none"><span></span></button>
            <!-- Side Header Logo Start -->
            <div class="side-header-logo pt-120 pt-lg-80 pt-md-80 pt-sm-80 pt-xs-50">
                <a href="{{ url_for('routes.home') }}">
                    <p><h3 class="block-title">Kymry Burwell</p>
                    <p><h5>バーウェル　キムリー</h5></p></a>
            </div><!-- Side Header Logo End -->

            <!-- ========== Left Navigation Menu ========== -->
            {% block nav %}
            {% endblock %}

            <!-- Side Header Logo Start -->
            <div class="side-header-footer pb-120 pb-lg-80 pb-md-80 pb-sm-80 pb-xs-50">

                <!-- Side Header Contact Information -->
                <div class="side-header-contact-info">
                    <p>+1 512 299 6270</p>
                    <p>kymry.burwell@gmail.com</p>
                    <p><a href="../static/resume_kymry_burwell.pdf">resume</a></p>
                </div>

                <!-- Side Header Social -->
                <div class="side-header-social">
                    <a href="https://www.linkedin.com/in/kymryburwell"><i class="fa fa-linkedin"></i></a>
                    <a href="https://www.github.com/kymry"><i class="fa fa-github"></i></a>
                </div>

                <!-- Side Header Copyright -->
                <div class="side-header-copyright">
                    <p></p>
                </div>

            </div><!-- Side Header Footer End -->

        </div><!-- Side Header Inner End -->

    </div><!-- Side Header End -->

    <!-- ========== SUBCLASS TEMPLATES ========== -->
    {% block content %}
    {% endblock %}

</div>

<!-- JS
============================================ -->

<!-- jQuery JS -->
<script src="../static/theme/assets/js/vendor/jquery-1.12.4.min.js"></script>
<!-- Popper JS -->
<script src="../static/theme/assets/js/popper.min.js"></script>
<!-- Bootstrap JS -->
<script src="../static/theme/assets/js/bootstrap.min.js"></script>
<!-- Plugins JS -->
<script src="../static/theme/assets/js/plugins.js"></script>
<!-- Ajax Mail -->
<script src="../static/theme/assets/js/ajax-mail.js"></script>
<!-- Main JS -->
<script src="../static/theme/assets/js/main.js"></script>
<!-- Google Map Api -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAlZPf84AAVt8_FFN7rwQY5nPgB02SlTKs"></script>
<!-- Google Map Activation -->
<script src="../static/theme/assets/js/map.js"></script>

</body>

</html>

app/application/templates/contact.html
<div data-anchor="contact" class="fp-section fp-auto-height-responsive">
    <div class="fp-section-inner pt-120 pt-lg-80 pt-md-80 pt-sm-80 pt-xs-50 pb-70 pb-lg-30 pb-md-30 pb-sm-20 pb-xs-0">
        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-12">
                    <div class="row">

                        <!-- Contact Form -->
                        <div class="col-lg-10 col-12 mb-50">
                            <div class="contact-form">
                                <h3>CONTACT FORM</h3>
                                <form id="contact-form" action="../static/theme/assets/php/mail.php" method="post">
                                    <input type="text" name="name" placeholder="Name">
                                    <input type="email" name="email" placeholder="Email">
                                    <textarea name="message" placeholder="Message"></textarea>
                                    <input type="submit" value="Send">
                                </form>
                                <p class="form-messege"></p>
                            </div>
                        </div>

                        <!-- Contact Info -->
                        <div class="col-lg-10 col-12 mb-50">
                            <div class="contact-info">
                                <h3>QUICK CONTACT</h3>
                                <ul>
                                    <li><span>Phone:</span> <a href="#">+012456879</a>, <a href="#">+012456878</a></li>
                                    <li><span>Email:</span> <a href="#">info@example.com</a>, <a href="#">contact@example.com</a></li>
                                    <li><span>Location:</span> 2020 Willshire Glen, Alpharetta, GA-30009</li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-lg-6 col-12">
                    <div class="row">

                        <!-- Contact Availability -->
                        <div class="col-lg-10 col-12 mb-50">
                            <div class="contact-availability">
                                <h3>24/7 ANYTIME</h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour lebmid</p>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered </p>
                            </div>
                        </div>

                        <!-- Contact Map -->
                        <div class="col-lg-10 col-12 mb-50">
                            <div id="contact-map"></div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

app/application/templates/home.html
{% extends "base.html" %}

{% block nav %}
    {% include 'left_nav_main.html' %}
{% endblock %}

{% block content %}
    <!-- Content Body Start -->
    <div class="content-body section">
        
        <!-- Full Page Start -->
        <div id="fullpage">

            {% include 'about.html' %}
            {% include 'projects.html' %}
            {% include 'thoughts.html' %}

        </div><!-- Full Page End -->
        
    </div><!-- Content Body End -->
{% endblock %}

app/application/templates/left_nav_main.html
<!-- Side Header Logo Start -->
<div class="side-header-menu">
    <nav id="side-menu" class="side-menu fullpage-menu">
        <ul>
            <li data-menuanchor="about"><a href="#about">About Me</a></li>
            <li data-menuanchor="service"><a href="#service">Projects</a></li>
            <li data-menuanchor="blog"><a href="#blog">Learning Resources</a></li>
        </ul>
    </nav>
</div><!-- Side Header Menu End -->

app/application/templates/left_nav_other.html
<!-- Side Header Logo Start -->
<div class="side-header-menu">
    <nav id="side-menu" class="side-menu fullpage-menu">
        <ul>
            <li data-menuanchor="about"><a href="/#about">About Me</a></li>
            <li data-menuanchor="service"><a href="/#service">Projects</a></li>
            <li data-menuanchor="blog"><a href="/#blog">Learning Resources</a></li>
        </ul>
    </nav>
</div><!-- Side Header Menu End -->

app/application/templates/project_sentiment.html
{% extends "base.html" %}

{% block nav %}
    {% include 'left_nav_other.html' %}
{% endblock %}

{% block content %}

<!-- Content Body Start -->
<div class="content-body section custom-scroll">

    <div class="section-wrap section pt-120 pt-lg-80 pt-md-80 pt-sm-80 pt-xs-50 pb-120 pb-lg-80 pb-md-80 pb-sm-80 pb-xs-50">
        <div class="container">
            <div class="row">

               <!-- Random Question Generation Section -->
               <div class="col-lg-6 col-12 mb-sm-45 mb-xs-45">
                   <div class="row">
                       <div class="col-lg-10 col-12 mb-45">
                           <div class="comment-form">
                               <input type="submit" onclick="get_question()" value="New Question">
                               <p class="form-messege sentiment_question" id="random-question">
                                   What are your thoughts on the final season of Game of Thrones?
                               </p>
                           </div>
                       </div>
                   </div>
                </div>

                <!-- Sentiment Analysis Section -->
                <div class="col-lg-6 col-12 mb-sm-45 mb-xs-45">
                    <div class="row">

                        <!-- Sentiment Analysis Form -->
                        <div class="col-lg-10 col-12 mb-45">
                            <div class="comment-form">
                                <form id="generate-question-form" action="" method="post" novalidate>
                                    {{ form.hidden_tag() }}
                                    <div class="row">
                                        <div class="col-12 mb-30">{{ form.body(placeholder="Answer") }}</div>
                                        <div class="col-12">{{ form.submit_review(type="submit", value="Sentiment Prediction") }}</div>
                                    </div>
                                     <p></p><p></p>

                                    {% if form.prediction.data %}
                                    <p class="form-messege">Your review was <b>{{ form.prediction.data }}.</b></p>
                                        <p><h5>Is the prediction correct?</h5></p>
                                            {{ form.submit_correct(type="submit", value="Yes", id="submit_1") }}
                                            {{ form.submit_incorrect(type="submit", value="No", id="submit_2") }}
                                    {% endif %}

                                    {% if reviewed %}
                                        <p>Thank you. How about answering another question?</p>
                                    {% endif %}

                                </form>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

</div><!-- Content Body End -->

<!---- JavaScript ---->
<script>
    function get_question() {
        $.ajax({
            type: 'POST',
            url: '/question',
            success: function(response) {
                document.getElementById('random-question').innerHTML=response;
            },
            error: function() {}})}
</script>

{% endblock %}

app/application/templates/projects.html
<div data-anchor="service" class="fp-section fp-auto-height-responsive">
    <div class="fp-section-inner pt-120 pt-lg-80 pt-md-80 pt-sm-80 pt-xs-50 pb-120 pb-lg-80 pb-md-80 pb-sm-80 pb-xs-50">
        <div class="container">
            <div class="row">

                <div class="col-xl-10 col-12 ml-auto mr-auto">
                    <div class="row">

                        <!-- Project One -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <div class="blog-content">
                                <h3 class="blog-title">Sentiment Analysis</h3>
                                <p>A shallow neural network for sentiment analysis built in Keras.</p>
                                <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                            </div>
                        </div>

                        <!-- Project Two -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <div class="blog-content">
                                <h3 class="blog-title">API Aggregation Web App</h3>
                                <p>Sentiment Analysis neural network built with Keras and trained with IMDB's review dataset.</p>
                                <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                            </div>
                        </div>

                        <!-- Project Three -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <div class="blog-content">
                                <h3 class="blog-title">Autonomous Drone Navigation</h3>
                                <p>A real-time algorithm for autonomous drone rerouting using multi-agent pathfinding techniques.
                                Research, developed and tested for my master's thesis.</p>
                                <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                            </div>
                        </div>

                        <!-- Project Four -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <div class="blog-content">
                                <h3 class="blog-title">Fake News Analysis</h3>
                                <p>To be filled in later</p>
                                <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/application/templates/thoughts.html
<div data-anchor="blog" class="fp-section fp-auto-height-responsive" style="background-image: url(../static/theme/assets/images/bg/service-bg.png)">
    <div class="fp-section-inner pt-120 pt-lg-80 pt-md-80 pt-sm-80 pt-xs-50 pb-50 pb-lg-10 pb-md-10 pb-sm-10 pb-xs-20">
        <div class="container">
            <div class="row">

                <div class="col-xl-10 col-12 ml-auto mr-auto">
                    <div class="row">

                        <!-- Project A -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <h3 class="blog-title">Sentiment Analysis</h3>
                            <p>Sentiment Analysis neural network built with Keras and trained with IMDB's review dataset.</p>
                            <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                        </div>

                        <!-- Project B -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <h3 class="blog-title">API Aggregation Web App</h3>
                            <p>Sentiment Analysis neural network built with Keras and trained with IMDB's review dataset.</p>
                            <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                        </div>

                         <!-- Project C -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <h3 class="blog-title">Drone Navigation (Master Thesis)</h3>
                            <p>Sentiment Analysis neural network built with Keras and trained with IMDB's review dataset.</p>
                            <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                        </div>


                        <!-- Project D -->
                        <div class="blog-item col-md-6 col-12 mb-40 mb-xs-30">
                            <h3 class="blog-title">Fake News Analysis</h3>
                            <p>Sentiment Analysis neural network built with Keras and trained with IMDB's review dataset.</p>
                            <p class="read-more"><a href="{{ url_for('routes.sentiment') }}">Go to project</a></p>
                        </div>


                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

app/application/templates/top.html
<div data-anchor="top" class="fp-section fp-auto-height-responsive">
    <div class="fp-section-inner pt-120 pt-lg-80 pt-md-80 pt-sm-80 pt-xs-50 pb-90 pb-lg-50 pb-md-50 pb-sm-50 pb-xs-20">
        <div class="container">
            <div class="row">

                <div class="hero-image col-md-6 col-12 mb-30"><img src="../static/theme/assets/images/hero/hero-1.jpg" alt=""></div>
                <div class="hero-image col-md-6 col-12 mb-30"><img src="../static/theme/assets/images/hero/hero-2.jpg" alt=""></div>

            </div>
        </div>
    </div>
</div>